const $=s=>document.querySelector(s); const money=n=>`$${Number(n||0).toLocaleString(undefined,{maximumFractionDigits:2})}`; const pct=n=>`${(Number(n||0)*100).toFixed(1)}%`;
let ops=[];
async function json(url,opts){const r=await fetch(url,opts);if(!r.ok){let d={};try{d=await r.json()}catch{};throw new Error(d.detail?.reasons?.join('；')||d.detail||`HTTP ${r.status}`)}return r.json()}
async function loadAccount(){const a=await json('/api/paper/account');$('#equity').textContent=money(a.equity);$('#exposure').textContent=money(a.exposure);const total=(a.equity-a.starting_cash);$('#pnl').textContent=`PnL ${money(total)}`;$('#pnl').className=total>=0?'good':'bad';$('#positions').innerHTML=a.positions.length?a.positions.map(p=>`<div class="position"><span>${p.market_id}<small class="sub">${p.outcome} · ${p.shares.toFixed(2)} shares</small></span><span class="${p.unrealized_pnl>=0?'good':'bad'}">${money(p.unrealized_pnl)}</span></div>`).join(''):'<div class="empty">暂无持仓</div>'}
async function scan(){ $('#opRows').innerHTML='<tr><td colspan="7" class="loading">正在读取行情和盘口…</td></tr>'; try{ops=await json('/api/opportunities?limit=12'); $('#marketCount').textContent=ops.length;$('#signalCount').textContent=ops.filter(x=>x.prediction.direction!=='PASS').length;$('#sourceText').textContent=(ops[0]?.market.source==='polymarket'?'Polymarket Live':'Demo Fallback');$('#sourceDot').style.background=ops[0]?.market.source==='polymarket'?'#63d7a6':'#f0aa43'; renderRows(); if(ops[0])renderDetail(ops[0]);}catch(e){$('#opRows').innerHTML=`<tr><td colspan="7" class="bad">${e.message}</td></tr>`}}
function renderRows(){ $('#opRows').innerHTML=ops.map((o,i)=>`<tr><td><span class="marketq">${o.market.question}</span><span class="sub">${o.market.category} · ${o.market.source}</span></td><td>${pct(o.prediction.market_probability)}</td><td>${pct(o.prediction.model_probability)}</td><td class="edge ${o.prediction.edge>=0?'pos':'neg'}">${o.prediction.edge>=0?'+':''}${pct(o.prediction.edge)}</td><td>${pct(o.prediction.confidence)}</td><td class="score">${o.features.opportunity_score.toFixed(1)}</td><td><button class="view" data-i="${i}">查看</button></td></tr>`).join(''); document.querySelectorAll('.view').forEach(b=>b.onclick=()=>renderDetail(ops[Number(b.dataset.i)]))}
function renderDetail(o){const p=o.prediction,f=o.features,m=o.market;$('#detailPanel h2').textContent=m.question;$('#detail').innerHTML=`<div class="probbox"><div><small>Market</small><strong>${pct(p.market_probability)}</strong></div><div><small>Model</small><strong>${pct(p.model_probability)}</strong></div></div><small class="sub">Probability Edge</small><div class="bar"><span style="width:${Math.min(100,Math.max(0,50+p.edge*250))}%"></span></div><div class="metrics"><div class="metric"><small>Direction</small><b>${p.direction}</b></div><div class="metric"><small>Spread</small><b>${pct(f.spread)}</b></div><div class="metric"><small>OB Imbalance</small><b>${f.orderbook_imbalance.toFixed(2)}</b></div></div><ul class="rationale">${p.rationale.map(x=>`<li>${x}</li>`).join('')}</ul><div class="tradebox"><input id="notional" type="number" min="1" value="100"><button class="trade" id="paperBuy">Paper 买入 ${p.direction==='NO'?'NO':'YES'}</button></div><div id="tradeMsg" class="sub" style="margin-top:8px"></div>`;$('#paperBuy').onclick=()=>paper(o)}
async function paper(o){const outcome=o.prediction.direction==='NO'?'NO':'YES';const notional=Number($('#notional').value);try{const r=await json('/api/paper/orders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({market_id:o.market.id,outcome,side:'BUY',notional})});$('#tradeMsg').textContent=`成交 ${r.trade.shares.toFixed(2)} shares @ ${r.trade.price.toFixed(3)}`;$('#tradeMsg').className='good';await loadAccount()}catch(e){$('#tradeMsg').textContent=`风控拒绝：${e.message}`;$('#tradeMsg').className='bad'}}
async function runBacktest(){try{const r=await json('/api/backtest/demo',{method:'POST'});$('#backtest').innerHTML=`<div class="probbox"><div><small>ROI</small><strong class="${r.roi>=0?'good':'bad'}">${pct(r.roi)}</strong></div><div><small>Max Drawdown</small><strong>${pct(r.max_drawdown)}</strong></div></div><div class="metrics"><div class="metric"><small>Trades</small><b>${r.trades}</b></div><div class="metric"><small>Win Rate</small><b>${pct(r.win_rate)}</b></div><div class="metric"><small>Sharpe*</small><b>${r.sharpe.toFixed(2)}</b></div></div><small class="sub" style="margin-top:10px">* 示例序列，仅验证回测/执行链路，不代表未来收益。</small>`}catch(e){$('#backtest').textContent=e.message}}
$('#refresh').onclick=scan;$('#backtestBtn').onclick=runBacktest; scan();loadAccount();
