const $=s=>document.querySelector(s);const money=n=>`$${Number(n||0).toLocaleString(undefined,{maximumFractionDigits:2})}`;const pct=n=>`${(Number(n||0)*100).toFixed(1)}%`;const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let ops=[];
async function json(url,opts){const r=await fetch(url,opts);if(!r.ok){let d={};try{d=await r.json()}catch{};throw new Error(d.detail?.reasons?.join('；')||d.detail||`HTTP ${r.status}`)}return r.json()}
async function loadAccount(){const a=await json('/api/paper/account');$('#equity').textContent=money(a.equity);$('#exposure').textContent=money(a.exposure);const total=a.equity-a.starting_cash;$('#pnl').textContent=`PnL ${money(total)}`;$('#pnl').className=total>=0?'good':'bad';$('#positions').innerHTML=a.positions.length?a.positions.map(p=>`<div class="position"><span>${esc(p.market_id)}<small class="sub">${esc(p.outcome)} · ${p.shares.toFixed(2)} shares</small></span><span class="${p.unrealized_pnl>=0?'good':'bad'}">${money(p.unrealized_pnl)}</span></div>`).join(''):'<div class="empty">暂无持仓</div>'}
async function loadCalibration(){try{const c=await json('/api/calibration/history');$('#calSamples').textContent=c.samples;$('#calScore').textContent=c.samples?`Brier ${Number(c.brier_score).toFixed(3)} · ECE ${Number(c.ece).toFixed(3)}`:'等待 resolved market'}catch{}}
async function loadEvents(){try{const rows=await json('/api/events');$('#events').innerHTML=rows.length?rows.slice(0,6).map(x=>`<div class="feed"><span><b>${esc(x.title)}</b><small>${esc(x.source)} · reliability ${pct(x.reliability)}</small></span><em class="${x.sentiment>=0?'good':'bad'}">${x.sentiment>=0?'+':''}${Number(x.sentiment).toFixed(2)}</em></div>`).join(''):'<div class="empty">暂无事件</div>'}catch(e){$('#events').innerHTML=`<div class="bad">${esc(e.message)}</div>`}}
async function loadAnomalies(){try{const rows=await json('/api/cross-market/graph-anomalies');$('#anomalies').innerHTML=rows.length?rows.slice(0,6).map(x=>`<div class="feed"><span><b>${esc(x.relation)}</b><small>${esc(x.explanation)}</small></span><em class="warn">${pct(x.severity)}</em></div>`).join(''):'<div class="empty">当前未发现明显概率约束异常</div>'}catch(e){$('#anomalies').innerHTML=`<div class="bad">${esc(e.message)}</div>`}}
async function scan(){$('#opRows').innerHTML='<tr><td colspan="7" class="loading">正在读取行情、盘口和模型…</td></tr>';try{ops=await json('/api/opportunities?limit=12');$('#marketCount').textContent=ops.length;$('#signalCount').textContent=ops.filter(x=>x.prediction.direction!=='PASS').length;$('#sourceText').textContent=ops[0]?.market.source==='polymarket'?'Polymarket Public Data':'Demo Fallback';$('#sourceDot').style.background=ops[0]?.market.source==='polymarket'?'#63d7a6':'#f0aa43';renderRows();if(ops[0])renderDetail(ops[0])}catch(e){$('#opRows').innerHTML=`<tr><td colspan="7" class="bad">${esc(e.message)}</td></tr>`}}
function renderRows(){$('#opRows').innerHTML=ops.map((o,i)=>`<tr><td><span class="marketq">${esc(o.market.question)}</span><span class="sub">${esc(o.market.category)} · ${esc(o.market.source)}</span></td><td>${pct(o.prediction.market_probability)}</td><td>${pct(o.prediction.model_probability)}</td><td class="edge ${o.prediction.edge>=0?'pos':'neg'}">${o.prediction.edge>=0?'+':''}${pct(o.prediction.edge)}</td><td>${pct(o.prediction.confidence)}</td><td class="score">${o.features.opportunity_score.toFixed(1)}</td><td><button class="view" data-i="${i}">查看</button></td></tr>`).join('');document.querySelectorAll('.view').forEach(b=>b.onclick=()=>renderDetail(ops[Number(b.dataset.i)]))}
async function renderDetail(o){const p=o.prediction,f=o.features,m=o.market;$('#detailPanel h2').textContent=m.question;$('#detail').innerHTML=`<div class="probbox"><div><small>Market</small><strong>${pct(p.market_probability)}</strong></div><div><small>Model</small><strong>${pct(p.model_probability)}</strong></div></div><small class="sub">Probability Edge</small><div class="bar"><span style="width:${Math.min(100,Math.max(0,50+p.edge*250))}%"></span></div><div class="metrics"><div class="metric"><small>Direction</small><b>${esc(p.direction)}</b></div><div class="metric"><small>Spread</small><b>${pct(f.spread)}</b></div><div class="metric"><small>OB Imbalance</small><b>${Number(f.orderbook_imbalance).toFixed(2)}</b></div></div><ul class="rationale">${p.rationale.map(x=>`<li>${esc(x)}</li>`).join('')}</ul><div id="evidence"><small class="sub">正在匹配事件证据…</small></div><div class="tradebox"><input id="notional" type="number" min="1" value="100"><button class="trade" id="paperBuy" ${p.direction==='PASS'?'disabled':''}>Paper 买入 ${p.direction==='NO'?'NO':'YES'}</button></div><div id="tradeMsg" class="sub"></div>`;$('#paperBuy').onclick=()=>paper(o);try{const e=await json(`/api/markets/${encodeURIComponent(m.id)}/evidence`);$('#evidence').innerHTML=`<div class="evidenceHead"><span>Evidence score ${pct(e.evidence_score)}</span><span>Sentiment ${Number(e.net_sentiment).toFixed(2)}</span></div>${e.evidence.length?e.evidence.slice(0,4).map(x=>`<div class="evidence"><b>${esc(x.title)}</b><small>${esc(x.source)} · ${pct(x.reliability)}</small></div>`).join(''):'<small class="sub">暂无高相关证据</small>'}`}catch(err){$('#evidence').innerHTML=`<small class="bad">Evidence unavailable: ${esc(err.message)}</small>`}}
async function paper(o){const outcome=o.prediction.direction==='NO'?'NO':'YES',notional=Number($('#notional').value);try{const r=await json('/api/paper/orders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({market_id:o.market.id,outcome,side:'BUY',notional})});$('#tradeMsg').textContent=`成交 ${r.trade.shares.toFixed(2)} shares @ ${r.trade.price.toFixed(3)}`;$('#tradeMsg').className='good';await loadAccount()}catch(e){$('#tradeMsg').textContent=`风控拒绝：${e.message}`;$('#tradeMsg').className='bad'}}
async function runBacktest(){try{const r=await json('/api/backtest/demo',{method:'POST'});$('#backtest').innerHTML=`<div class="probbox"><div><small>ROI</small><strong class="${r.roi>=0?'good':'bad'}">${pct(r.roi)}</strong></div><div><small>Max Drawdown</small><strong>${pct(r.max_drawdown)}</strong></div></div><div class="metrics"><div class="metric"><small>Trades</small><b>${r.trades}</b></div><div class="metric"><small>Win Rate</small><b>${pct(r.win_rate)}</b></div><div class="metric"><small>Sharpe*</small><b>${Number(r.sharpe).toFixed(2)}</b></div></div><small class="sub">* 示例序列只验证链路，不代表未来收益。</small>`}catch(e){$('#backtest').textContent=e.message}}
async function refreshAuto(){try{const s=await json('/api/auto/status');$('#autoBtn').textContent=s.running?'停止自动 Paper':'启动自动 Paper';$('#autoBtn').dataset.running=s.running?'1':'0'}catch{}}
async function toggleAuto(){try{const running=$('#autoBtn').dataset.running==='1';await json(running?'/api/auto/stop':'/api/auto/start',{method:'POST'});await refreshAuto();if(!running)setTimeout(()=>{scan();loadAccount()},800)}catch(e){alert(e.message)}}
$('#refresh').onclick=()=>Promise.all([scan(),loadEvents(),loadAnomalies(),loadCalibration()]);$('#backtestBtn').onclick=runBacktest;$('#autoBtn').onclick=toggleAuto;Promise.all([scan(),loadAccount(),loadEvents(),loadAnomalies(),loadCalibration(),refreshAuto()]);setInterval(refreshAuto,5000);
